#!/usr/bin/env bash
# This script lists all running processes and shows only those containing "bash" (excluding the grep process itself)

# shellcheck disable=SC2009
ps aux | grep bash | grep -v grep
