#!/usr/bin/env bash
# Display PID and process name for processes containing "bash" on Windows

tasklist | grep -i bash | while read -r line; do
    pname=$(echo "$line" | awk '{print $1}')
    pid=$(echo "$line" | awk '{print $2}')
    echo "$pid $pname"
done
