#!/usr/bin/env bash
# Infinite loop script that prints a message and handles SIGTERM

# Trap SIGTERM and print message immediately
trap 'printf "I am invincible!!!\n"' SIGTERM

# Infinite loop
while true
do
    printf "To infinity and beyond\n"
    sleep 2
done
