#!/usr/bin/env bash
# Infinite loop script that prints a message and handles SIGTERM

# Trap SIGTERM and print message immediately
trap 'printf "I am invincible!!!\n"' SIGTERM

while true
do
    printf "I am invicible!!!\n"
    sleep 2
done

